name: Update Status

on:
  repository_dispatch:
    types: [update-status]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Files
        run: |
          STATUS="${{ github.event.client_payload.status }}"
          TAGS='${{ github.event.client_payload.tags }}'
          NEWS="${{ github.event.client_payload.news }}"
          
          if [ "$STATUS" = "online" ]; then
            SED_STATUS="true"
          else
            SED_STATUS="false"
          fi
          
          sed -i "s/updateStatus(.*);/updateStatus($SED_STATUS, $TAGS);/g" index.html
          sed -i 's|<span id="newsText" class="notice-text">.*</span>|<span id="newsText" class="notice-text">'"$NEWS"'</span>|g' index.html

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update status via admin panel"
          git push
